### ISSUE TITLE
Lots of errors from Ephemeris about PROGMEM

### ISSUE THREAD

**Issue by kbahey** [hjd1964/SmartHandController#2]
I have the Ephemeris library installed from the Library Manager (not manually from git) and it is the latest available version.

When compiling, I get the following errors, and much much more of the same. 

Here is an excerpt:

```
In file included from ../Arduino/libraries/Ephemeris/Ephemeris.hpp:32,
                 from ../Arduino/libraries/Ephemeris/Ephemeris.h:23,
                 from sketch/src/commands/LX200.cpp:4:
../Arduino/libraries/Ephemeris/VSOP87.hpp:25:21: error: 'PROGMEM' does not name a type
 #define CONST const PROGMEM
                     ^~~~~~~
../Arduino/libraries/Ephemeris/VSOP87.hpp:43:1: note: in expansion of macro 'CONST'
 CONST VSOP87Coefficient L0MercuryCoefficients[]
 ^~~~~
../Arduino/libraries/Ephemeris/VSOP87.hpp:25:21: note: the macro 'PROGMEM' had not yet been defined
 #define CONST const PROGMEM
                     ^~~~~~~
../Arduino/libraries/Ephemeris/VSOP87.hpp:43:1: note: in expansion of macro 'CONST'
 CONST VSOP87Coefficient L0MercuryCoefficients[]
 ^~~~~
```

**Comment by kbahey** [comment]
The underlying reason here is that the ESP32 chokes on code in the Ephemeris' VSOP87.hpp and ELP2000.hpp

Specifically this code:

```
#if ARDUINO
#define CONST const PROGMEM
#else
#define CONST const
#endif
```

Changing that to just:

```
#define CONST const
```

Makes it compile and run successfully on an ESP32 SHC. 

Not sure if we should report this to Sebastien, to change the ARDUINO ifdef or what.

Thoughts?

**Comment by kbahey** [comment]
Found a solution to this, which is in pull request #3.

**Comment by hjd1964** [comment]
As mentioned this has already been handled by using my branch of the Ephemeris.

**Comment by kbahey** [comment]
Well, it works with the official Ephemeris library too. So all is well.

**Comment by kbahey** [comment]
Actually, no. 
My fork has the conditional on ESP32, and that is why it works.
